### ISSUE TITLE
Using this sdk with the Superannotate Desktop App

### ISSUE THREAD

**Issue by dhirajsuvarna** [superannotateai/superannotate-python-sdk#11]
Hi, 

I have used Superannotate Desktop App to annotate my images. 

Now I am trying to convert this into "coco format". I observed a hyperlink which directed me to this [github repo](https://github.com/superannotateai/annotateonline-input-converters) and from there I was redirected to this particular repo. 

Now my question is can I achieve my goal using this particular sdk?
Here is my code to convert the SA files to COCO file format 

```
import superannotate as sa

input_folder = r"C:\drive\project\project_ocr\data_dump\anno_monitor_images\train"
output_folder = r"C:\Users\dhiraj.suvarna\AppData\Local\Temp\out"
dataset_format = "COCO"
dataset_name = "patient_monitor_screen"
project_type = "Vector"
task = "object_detection"

sa.export_annotation(input_folder, output_folder, dataset_format, dataset_name, project_type, task)

```

when I execute this I get an error saying - 

```
PermissionError: [Errno 13] Permission denied: C:\Users\dhiraj.suvarna\AppData\Local\Temp\out
```
Please note that I have already tried - 
1. to run the script in admin mode 
2. changed the folder location to `temp` to avoid an permission issue. 

Any help is highly appreciated.

**Comment by hovnatan** [comment]
Hi.

The converters are indeed now integrated into SDK, but the SDK functionality is designed to work only with PRO users of the web platform. You can write the converter yourself by familiarizing with SuperAnnotate annotation format at https://github.com/opencv-ai/superannotate#format 

Thanks.
