### ISSUE TITLE
db/images/get_image_metadata returning list instead of dictionary

### ISSUE THREAD

**Issue by sritee** [superannotateai/superannotate-python-sdk#12]
`get_image_metadata` in db/images.py is returning a list rather than dictionary. This is causing `sa.upload_image_annotations` to fail, as it's trying to access dictionary items. `list indices must be integers or slices, not str`

It looks like calling the .json() on line 162 of db/images.py results in  list of multiple elements, despite there being only one image in the remote project. This causes the function to return a list, rather than doing the metadata[0] statement in line 182.

**Comment by hovnatan** [comment]
Hi, `sa.upload_image_annotations` works only for a single image. How do you use it?

**Comment by sritee** [comment]
the usage is `sa.upload_image_annotations(remote_project_name, image_name, annotation)`. 

image_name is a string. 

the line `image = get_image_metadata(project, image_name)` returns a list of 3 elements, despite the remote project only containing a single image with this name. Even if there are multiple such elements (which would be weird, and not so in this case), i would expect it be handled more smoothly.

**Comment by hovnatan** [comment]
Sorry, I couldn't reproduce your issue. Can you please provide more details?

**Comment by hovnatan** [comment]
I fixed an issue regarding deleted images in 3.2.6. Your issue might be related to it. Could you please try again with the new version? Thanks.

**Comment by sritee** [comment]
Hi, that fix for deleted images resolved the problem. Thanks!
