### ISSUE TITLE
Exporting annotations messes with attributes names

### ISSUE THREAD

**Issue by MathieuHaller** [superannotateai/superannotate-python-sdk#13]
Hello,

When I export the annotations of my project (only the annotations, without the images) using the desktop version of SuperAnnotate, all the jsons get assigned the most recent attribute name instead of their respective attribute name.

For example, if I have a "image quality" attribute group with the following attributes names:  
```["1", "2", "3", "4", "5"]  ```
with respective attribute ids (automatically affected by SuperAnnotate):  
```[1, 2, 3, 4, 5]```

Once I export the annotations, ALL jsons with an "image_quality" attribute will get the "5" name for their attribute, regardless of their actual assigned quality value.
  
I'd also like to pinpoint that despite this, the id seems to get exported fine.
For example an image with image quality "2" will, in its exported json, have:
```
"attributes" : [ {"id" : 2, ..., "name" : "5"}]
```

When it should be:
```
"attributes" : [ {"id" : 2, ..., "name" : "2"}]
```

This poses an issue when later using superannotate.aggregate_annotations_as_df(), as the id of the attribute is not translated to the pandas dataframe, only the attribute name.  
So we end up with a pandas dataframe where every image has "5" in the attributeName column, and the quality of the image is thus unknown.

Thank you for your time.

**Comment by hovnatan** [comment]
Hi. Thanks for the report. We confirmed that this is an issue with the desktop app. We will fix as soon as possible.
