### ISSUE TITLE
Throwing Key_error

### ISSUE THREAD

**Issue by MayStepanyan** [superannotateai/superannotate-python-sdk#27]
Hi

I have a bunch of COCO-format .json files which I want to convert to SA, and I'm using sa.import_annotations method for it. When I choose:   

project_type = 'Pixel', 
task='panoptic_segmentation'

it throws a Key Error 
 
![image](https://user-images.githubusercontent.com/51966224/118483160-c1067c00-b726-11eb-81ae-dc7a19e82afc.png)

when I choose instance_segmentation paired with either Pixel or Vector, the conversion works as it should

I tried the same conversion with the original COCO dataset, but again, I have the same error
![image](https://user-images.githubusercontent.com/51966224/118483740-71748000-b727-11eb-91c7-b2ed6b5da12c.png)

Are there any ideas about what I'm doing wrong?

**Comment by rcmanga** [comment]
Hey!
Can you attach a small example of COCO annotation that fails to be converted?

**Comment by MayStepanyan** [comment]
> Hey!
> Can you attach a small example of COCO annotation that fails to be converted?

Hi. Here's an example from the original COCO dataset

[instances_val.zip](https://github.com/superannotateai/superannotate-python-sdk/files/6493817/instances_val.zip)

**Comment by rcmanga** [comment]
The attached example is COCO JSON for the task of instance segmentation, and hence it can not be converted as panoptic segmentation. Please check the official [documentation](https://cocodataset.org/#format-data)  for COCO panoptic segmentation. 
Hope this helps )

**Comment by MayStepanyan** [comment]
> The attached example is COCO JSON for the task of instance segmentation, and hence it can not be converted as panoptic segmentation. Please check the official [documentation](https://cocodataset.org/#format-data) for COCO panoptic segmentation.
> Hope this helps )

Oh, seems like my other json files are designed for the instance segmentation task too. Didn't know there is such a difference since all the COCO annotations share the same basic structure, will do some research  

Thanks!
