### ISSUE TITLE
Problem with importing json annotations in Desktop application

### ISSUE THREAD

**Issue by MayStepanyan** [superannotateai/superannotate-python-sdk#28]
Hi. 

I'm testing SuperAnnotate and I have an issue with uploading pre-existing annotation files. I converted my coco annotations to sa format as shown in your instruction [here](https://doc.superannotate.com/docs/working-with-annotation-formats) , and I tried to change the parameters in the sa.import_annotation method (such as task and project_type), but it didn't help. I made example annotations from scratch via SA, downloaded them and tried to upload json files again ― same result. I even tried to download the annotations from your predefined "Example Project(SuperAnnotate)" and upload them again: didn't work either. Application just says that the uploading is failed and I need to make sure I'm using SA format. 

![Screenshot from 2021-05-17 15-14-29](https://user-images.githubusercontent.com/51966224/118608459-c5847080-b7ca-11eb-98bc-227f123f8f74.png)

Can you help me to solve this problem please?  

You can find some examples of json files below. I tried to upload them separately on separate projects. If needed, I can provide the class documents too, which I upload BEFORE uploading the annotations. 

[jsons.zip](https://github.com/superannotateai/superannotate-python-sdk/files/6499120/jsons.zip)

**Comment by rcmanga** [comment]
Hey, 

The annotation format used in Desktop App is different from the one used in our WEB platform. Please check the official GitHub repo for the Desktop App for [details](https://github.com/opencv-ai/superannotate). You can find an example annotation [here](https://github.com/opencv-ai/superannotate/tree/master/Example%20Project%20-%20Lvis_101%20-%20rear%20classes).  Perhaps you can write a simple parser to convert your annotations from SuperAnnotate WEB to Desktop format.
 As a side note, all SDK functions are built for the WEB platform.

**Comment by MayStepanyan** [comment]
Hi, 
Thanks! I'll take that difference into account in the future
