### ISSUE TITLE
Don't require GUI version of OpenCV

### ISSUE THREAD

**Issue by kevin-hanselman** [superannotateai/superannotate-python-sdk#624]
The Python package `opencv-python` requires third-party GUI libraries to be installed when running `import cv2`. This project does not use any GUI functionality in OpenCV and could therefore remove this dependency on third-party libraries by depending on `opencv-python-headless` instead.

See the [opencv-python docs](https://github.com/opencv/opencv-python#installation-and-usage) for more information.

**Comment by VaghinakDev** [comment]
In the coming release we will remove cv2 from dependencies

**Comment by kevin-hanselman** [comment]
OpenCV with libGL is still a dependency.
