### ISSUE TITLE
Unpin Specific Patch-Level Package Requirements

### ISSUE THREAD

**Issue by jackhamburger** [superannotateai/superannotate-python-sdk#633]
We are having some challenges using Superannotate while upgrading peer dependencies with security concerns due to the requirements specifications strategy of this python package. 

Specifically, we ran into an issue recently with tqdm and requests where other packages which we needed to upgrade depended on tqdm ^4.64.1. While I would recommend moving to a system where you depend on a common major and minimum minor version, I understand that could have potential impacts on reproducibility and robust testing. Minimally, it would be great to not pin a patch version (as improvements in patches should only fix previously broken functionality).

Please advise.

**Comment by VaghinakDev** [comment]
The update will be included in the next release.

**Comment by VaghinakDev** [comment]
Updated in version v4.4.15
