### ISSUE TITLE
Relax pillow dependency version constraint

### ISSUE THREAD

**Issue by mklefstad** [superannotateai/superannotate-python-sdk#644]
Hi - we are having some difficulties using superannotate as the current version constraint for `pillow` specified in the requirements.txt conflicts with our desired version. 

Specifically, the superannotate requirement is `pillow~=9.5` but we'd like to be able to use the next major version (pillow version 10.0.0). 

Could the requirements be updated to allow pillow versions with a major version of 10?

**Comment by VaghinakDev** [comment]
Hi, will be updated in the coming release.

**Comment by cpbSensorum** [comment]
This is affecting me too (for security reasons). How long until the fix is released?

**Comment by VaghinakDev** [comment]
Dependency restriction updated in the v4.4.16 
https://pypi.org/project/superannotate/4.4.16/
