### ISSUE TITLE
Support Pydantic V2

### ISSUE THREAD

**Issue by Jinior** [superannotateai/superannotate-python-sdk#646]
Hi,

We are having issues using superannotate together with our internal tooling because of a different Pydantic version.  Would it be possible to support pydantic V2?

According to the migration guide it is possible to support the new version by only changing the import statements: https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features
They support this by adding the `pydantic.v1` module which contains the api from version 1.

**Comment by VaghinakDev** [comment]
Hi, thank you for your feedback, we plan to migrate to Pydantic V2 in the coming releases

**Comment by VaghinakDev** [comment]
Dependency restriction updated in the v4.4.16 
https://pypi.org/project/superannotate/4.4.16/

**Comment by Jinior** [comment]
Thank you for solving the issue so promptly!
