### ISSUE TITLE
No function to modify project settings after creation?

### ISSUE THREAD

**Issue by angus-dawson-idexx** [superannotateai/superannotate-python-sdk#647]
On `SAClient` there is a `get_project_settings` method, but no corresponding method to set project settings after creation. The `set_project_default_image_quality_in_editor` method uses `self.controller.projects.set_settings`, so the functionality exists in the implementation, but it would be useful to be able to change e.g. the default fill opacity or arbitrary other project settings, like you can when creating a project with `create_project`.

Since the `controller` attribute is not mentioned in the documentation, I am hesitant to use `<sa_client>.controller.projects.set_settings` directly.

**Comment by VaghinakDev** [comment]
Thank you for your feedback, we will take this into account in our future releases.
