### ISSUE TITLE
prepare_export method does not work properly

### ISSUE THREAD

**Issue by GurayOzgodek** [superannotateai/superannotate-python-sdk#654]
After upgrading superannotate python sdk version from 4.4.12 to 4.4.16, although i marked 'Completed' the 'annotation_statuses' parameter in prepare_export function, it still downloads all annotation types (InProgress, NotStarted etc.).

```
new_export = sa_client.prepare_export(project=project_name, annotation_statuses=["Completed"])

sa_client.download_export(project=project_name,
                                  export=new_export,
                                  folder_path=dataset_all_path,
                                  extract_zip_contents=True)
```

Thank you for help

**Comment by VaghinakDev** [comment]
The issue was resolved on November 22, 2023 and there is no need to update the SDK.
