### ISSUE TITLE
Support Pandas V2

### ISSUE THREAD

**Issue by Jinior** [superannotateai/superannotate-python-sdk#656]
Hi,

Thank you again for fixing compatibility with Pydantic V2. #646

The final hurdle we have to integrate superannotate with our internal tooling  is Pandas ^2.0 support. Would it be possible to support Pandas 2.0?

According to the changelog almost all breaking API changes have to do with datetime obejcts; our own codebase was compatible with pandas 2.0 without making any adjustments (apart from incrementing the version in the requirements.txt). https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#backwards-incompatible-api-changes

**Comment by VaghinakDev** [comment]
Hi, yes we will update the dependency in the coming release (v4.4.17).

**Comment by Jinior** [comment]
Thanks!

Any indication as to when the coming release will be released so I can update my team?

**Comment by VaghinakDev** [comment]
The next release will be on December 21, 2023.
