### ISSUE TITLE
Updating the jsonschema version in requirements.txt

### ISSUE THREAD

**Issue by saunair** [superannotateai/superannotate-python-sdk#657]
Hi Superannotate team, our internal codebase is broken due to the strict `jsonschema` version requirement for superannotate-pip. Could we relax the constraint here for the next release. 
The specific build error we're facing is: ` Draft7Validator(
TypeError: __init__() got an unexpected keyword argument 'registry'`

This is because of the outdated version of json set here.

**Comment by VaghinakDev** [comment]
The new version of `jsonschema` has problems due to schema validation, and in the upcoming release `4.4.18`, we will simplify this dependency.

**Comment by VaghinakDev** [comment]
This is fixed in version v4.4.18

**Comment by saunair** [comment]
@VaghinakDev apologies for the delay. Thanks for fixing this! 
Curious, is there a possibility of a release without moving pandas to 2.0?
