### ISSUE TITLE
superannotate 4.4.21 depends on pre-release version of superannotate-schemas

### ISSUE THREAD

**Issue by Jinior** [superannotateai/superannotate-python-sdk#687]
When installing superannotate==4.4.21 using the `uv pip` package manager we get the following error message:
```
superannotate-schemas was requested with a pre-release marker (e.g., superannotate-schemas==1.0.47b5), but pre-releases weren't enabled (try: `--prerelease=allow`)
```
The problem exists for superannotate versions >= 4.4.18 (changed in this commit: 0c29c15c6747faec87de498772078b08bfe79df9)

On PyPI I can see that 1.0.47 (non-beta) is already released. Would it be possible to update to this version?

Due to how we package our own software enabling pre-releases would be a problem for us.

**Comment by VaghinakDev** [comment]
Thank you for opening the issue. The fix will be available on June 13 in version 4.4.22.
