### ISSUE TITLE
Merge projects feature is needed.

### ISSUE THREAD

**Issue by abulus** [superannotateai/superannotate-python-sdk#692]
Hi dear devs,

For example I have a project named Echo, and Hotel. I want to merge these two projects with a new name of Tango. 

For this action, I am downloading both annotations and images to local, then create new project and upload those images and annotations to that new project.

It is time consuming and not optimal. 

Like we have clone option, we should have move option or something like this to perform this action.

If I am missing any points regarding merging operations please inform me. 

I hope my issue is clear to understand, thank you.

**Comment by VaghinakDev** [comment]
Hello,
Thank you for reaching out with your question.
We understand the need for a more efficient way to merge projects. While we discuss your feature request with our product team, we recommend an alternative workflow that leverages cloud storage for better efficiency. Here’s how you can streamline the process:
Integrate with Cloud Storage: Set up integration with a cloud storage service (e.g., AWS, GCP). Create separate folders for your data (e.g., folders “Echo” and “Hotel”).
Clone Projects: Use the [sa.clone_project()](https://superannotate.readthedocs.io/en/develop/api_reference/api_project.html#superannotate.SAClient.clone_project) 
 command to clone your projects’ set up and classes.
Attach Items from Integrated Storage: Execute the sa.attach_items_from_integrated_storage() [[link]](https://superannotate.readthedocs.io/en/develop/api_reference/api_project.html#superannotate.SAClient.attach_items_from_integrated_storage) command and select the necessary folders (Echo and Hotel) to attach the items to your new project.
Handle Annotations:
Retrieve annotations using the sa.get_annotations() [[link]](https://superannotate.readthedocs.io/en/develop/api_reference/api_annotation.html#superannotate.SAClient.get_annotations) command and save them to memory to avoid using local storage.
Upload the annotations to the new project using the sa.upload_annotations() [[link]](https://superannotate.readthedocs.io/en/develop/api_reference/api_annotation.html#superannotate.SAClient.upload_annotations) command.
This method should save you time by avoiding repetitive local downloads and uploads.
Let us know if you have any further questions or need additional assistance.
Best regards
