### ISSUE TITLE
Cannot use your sdk without a team token

### ISSUE THREAD

**Issue by happyCodingSusan** [superannotateai/superannotate-python-sdk#8]
Hi Superannotate team, thank you for sharing your great work!

I downloaded your SDK. While I found I am not able to test your SDK without initializing the SDK. In order to initialize it with "superannotatecli init", I need a team token. With a free account, I could not find where to create a team token. I am writing to check with you if I can test your SDK with a free account or not.  

Many Thanks

**Comment by hovnatan** [comment]
Hi,

Sorry, we currently allow SDK to PRO accounts. Only functions that don't access online platform, e.g., annotation format converters, will work with a free account.

Thanks,
Hovnatan
